// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1ztmhhs-_4hQazGOYVGeu7IRHlr2g1GU',
    appId: '1:21899928787:web:16659b970001c8f859a026',
    messagingSenderId: '21899928787',
    projectId: 'testing-cli-2ae0b',
    authDomain: 'testing-cli-2ae0b.firebaseapp.com',
    storageBucket: 'testing-cli-2ae0b.firebasestorage.app',
    measurementId: 'G-2QMXH3Y1MD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQxhXsJXNIgxaedureiJ53RWRjbX_YppQ',
    appId: '1:21899928787:android:50666ef549ad320159a026',
    messagingSenderId: '21899928787',
    projectId: 'testing-cli-2ae0b',
    storageBucket: 'testing-cli-2ae0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9p5kxEpd2evSXE-EEm1pLJFbnqMdiI0c',
    appId: '1:21899928787:ios:d160a26e937a88d959a026',
    messagingSenderId: '21899928787',
    projectId: 'testing-cli-2ae0b',
    storageBucket: 'testing-cli-2ae0b.firebasestorage.app',
    iosBundleId: 'com.techease.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9p5kxEpd2evSXE-EEm1pLJFbnqMdiI0c',
    appId: '1:21899928787:ios:d160a26e937a88d959a026',
    messagingSenderId: '21899928787',
    projectId: 'testing-cli-2ae0b',
    storageBucket: 'testing-cli-2ae0b.firebasestorage.app',
    iosBundleId: 'com.techease.firebaseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1ztmhhs-_4hQazGOYVGeu7IRHlr2g1GU',
    appId: '1:21899928787:web:3ed0c21650a45a5e59a026',
    messagingSenderId: '21899928787',
    projectId: 'testing-cli-2ae0b',
    authDomain: 'testing-cli-2ae0b.firebaseapp.com',
    storageBucket: 'testing-cli-2ae0b.firebasestorage.app',
    measurementId: 'G-R6FBJH58NK',
  );
}
